// pages/index.tsx
import RewardSystem from "@/utils/RewardSystem";
import { useOpenFormat, useWallet } from "@openformat/react";
import Head from "next/head";
import React from "react";
import toast from "react-hot-toast";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { address } = useWallet();
  const { sdk } = useOpenFormat();

  const rewardSystem = new RewardSystem(sdk);

  async function handleConnect() {
    if (address) {
      // Add loading toast
      const loadingToastId = toast.loading(
        "Processing... this can take a while depending on chain network conditions."
      );

      const user = await rewardSystem.handleCompletedAction(address, "connect");

      // Dismiss loading toast
      toast.dismiss(loadingToastId);

      for (const token of user.rewarded) {
        let message = `Thank you for completing the `;
        if (token.activityType === "ACTION") {
          message += `action ${token.id}`;
        } else if (token.activityType === "MISSION") {
          message += `mission ${token.id}`;
        }
        message += `, you have received ${token.amount} ${token.type}`;
        toast.success(message, {
          duration: 5000,
        });
      }
    }
  }

  return (
    <>
      <Head>
        <title>Create OpenFormat Dapp</title>
        <meta
          name="description"
          content="Generated by create-openformat-dapp"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by heading to&nbsp;
            <code className={styles.code}>README.md</code>
          </p>
          <div>
            <Link
              href="https://openformat.tech"
              target="_blank"
              rel="noopener noreferrer"
            >
              By <p>OPENFORMAT</p>
            </Link>
          </div>
        </div>

        <div className={styles.center}>
          <p className={styles.title}>Dapp Wrap</p>
          <div className={styles.buttoncontainer}>
            <button className={styles.button} onClick={handleConnect}>
              Trigger Action
            </button>
          </div>
        </div>

        <div className={styles.grid}>
          <Link
            href="https://openformat.tech"
            className={styles.description}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={styles.h2}>Docs</h2>
            <p className={inter.className}>
              Find in-depth information about OPENFORMAT
            </p>
          </Link>

          <Link
            href="https://openformat.tech"
            className={styles.description}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={styles.h2}>Bounties</h2>
            <p className={inter.className}>
              Discover developer bounties at our GitHub
            </p>
          </Link>

          <Link
            href="https://openformat.tech"
            className={styles.description}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={styles.h2}>Templates</h2>
            <p className={inter.className}>
              Discover and deploy boilerplate template Dapps.
            </p>
          </Link>
        </div>
      </main>
    </>
  );
}
